#!/bin/sh

SLACK_POST_URL="https://slack.com/api/chat.postMessage"

YOUR_API_TOKEN=""
CHANNEL_NAME="my-schedule-board"

curl -X POST ${SLACK_POST_URL} \
-d "token=${YOUR_API_TOKEN}" \
-d "channel=#${CHANNEL_NAME}" \
-d "as_user=true" \
-d "text=$1"

#特定の相手にtextを送信する場合は以下の通りtextを設定する
<!channel> チャンネル全体
<!here> チャンネルのActiveユーザー全体
<@user> 特定のユーザー

例)
-d "text=<!channel> チャンネル全体に伝える！"

 # API Tokenの持ち主（この場合は作成したbot）として発言する
#-d "as_user=true" \

#以下の2つを変更する場合は、as_user=trueを外すこと。
# API Tokenの持ち主（この場合は作成したbot）として発言するため、名前等を指定しても無駄になる。

#アイコンを変えられる
# 絵文字
#-d icon_emoji=':simple_smile:' \
# アイコン
#-d "icon_url="

# ユーザ名を変えられる
#-d "username=TrapBot" \
